### ISSUE TITLE
Checklist fix, ajout & update chunk

### ISSUE THREAD

**Issue by Clem-Fern-Dev** [Clem-Fern-Dev/SpongePlugin#24]
### **Messages d'informations** 

- [ ] Messages lors de l'entrée/sortie d'un chunk claim ne nous appartenant pas & sans autorisation accordé
- [ ] Messages lors de l'entrée/sortie d'un chunk claim avec autorisation ou nous appartenant
- [x] Messages claim/unclaim
- [x] Messages d'ajout de permissions
- [ ] Messages d'autorisation ou non de modification/drop du chunk

### **Protections des chunks** 
- [ ] Break & place block event
- [ ] Interact item & block
- [ ] Use bug
- [ ] explosion
- [ ] propagation du feux

### **Commandes** 
- [x] Commandes de claim & unclaim
- [x] Commandes d'ajout & de suppression de permissions sur un joueur
- [ ] Commandes d'autorisation d'explosion, de propagation des flammes & de drops d'item sur un chunk
- [ ] Commandes pour les admins

**Comment by Clem-Fern-Dev** [comment]
Autre système de chunk utilisé.
